const {
  withDangerousMod,
  withXcodeProject,
} = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Fix for react-native-permissions on RN 0.81 + Expo SDK 54.
 *
 * Problem: Expo's EXAppDelegateWrapper implements getModuleClassFromName:
 * by delegating to RCTDefaultReactNativeFactoryDelegate which returns nil.
 * It doesn't implement getModuleProvider: so RCTModuleProviders is never used.
 * Result: third-party TurboModules like RNPermissions are invisible at runtime.
 *
 * Fix: Swizzle getModuleClassFromName: on EXAppDelegateWrapper to check for
 * RNPermissions before falling through to the original implementation.
 */

const OBJC_FILE_NAME = "RNPermissionsModuleRegistration.mm";
const PROJECT_NAME = "permissionhandlerexample";

const OBJC_CONTENT = `// Auto-generated by withRNPermissionsModuleProvider config plugin.
#import <Foundation/Foundation.h>
#import <objc/runtime.h>

static IMP _original_getModuleClassFromName = NULL;

static Class _swizzled_getModuleClassFromName(id self, SEL _cmd, const char *name) {
  if (name && strcmp(name, "RNPermissions") == 0) {
    Class cls = NSClassFromString(@"RNPermissions");
    if (cls) return cls;
  }
  if (_original_getModuleClassFromName) {
    return ((Class (*)(id, SEL, const char *))_original_getModuleClassFromName)(self, _cmd, name);
  }
  return nil;
}

__attribute__((constructor))
static void _registerRNPermissions(void) {
  // Swizzle EXAppDelegateWrapper's getModuleClassFromName:
  Class wrapperClass = NSClassFromString(@"EXAppDelegateWrapper");
  if (!wrapperClass) return;

  SEL sel = @selector(getModuleClassFromName:);
  Method method = class_getInstanceMethod(wrapperClass, sel);
  if (!method) return;

  _original_getModuleClassFromName = method_setImplementation(method, (IMP)_swizzled_getModuleClassFromName);
}
`;

function withCodegenPatch(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      // Patch codegenConfig
      const pkgPath = path.join(
        config.modRequest.projectRoot,
        "node_modules",
        "react-native-permissions",
        "package.json"
      );

      if (fs.existsSync(pkgPath)) {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
        if (pkg.codegenConfig && !pkg.codegenConfig.ios?.modulesProvider) {
          pkg.codegenConfig.ios = pkg.codegenConfig.ios || {};
          pkg.codegenConfig.ios.modulesProvider = {
            RNPermissions: "RNPermissions",
          };
          fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
        }
      }

      // Write the ObjC swizzle file
      const objcPath = path.join(
        config.modRequest.platformProjectRoot,
        PROJECT_NAME,
        OBJC_FILE_NAME
      );
      fs.writeFileSync(objcPath, OBJC_CONTENT);

      return config;
    },
  ]);
}

function withXcodeFile(config) {
  return withXcodeProject(config, async (config) => {
    const project = config.modResults;

    if (!project.hasFile(`${PROJECT_NAME}/${OBJC_FILE_NAME}`)) {
      project.addSourceFile(
        `${PROJECT_NAME}/${OBJC_FILE_NAME}`,
        { target: project.getFirstTarget().uuid },
        project.findPBXGroupKey({ name: PROJECT_NAME }) ||
          project.findPBXGroupKey({ path: PROJECT_NAME })
      );
    }

    return config;
  });
}

module.exports = function withRNPermissionsModuleProvider(config) {
  config = withCodegenPatch(config);
  config = withXcodeFile(config);
  return config;
};
